kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  proxy-protocol: "true"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "192.168.1.100"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  use-proxy-protocol: "true"
  proxy-protocol: "true"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "192.168.1.100"